### ISSUE TITLE
Jetson TX2 

### ISSUE THREAD

**Issue by Davidnet** [resin-io-playground/kernel-module-build#4]
Hi! The provided example doesn't work on Jetson TX2, on 2.7.4+rev2.prod

**Comment by imrehg** [comment]
@Davidnet don't think there's a `2.7.4+rev2.prod` version released in production, where do you get that version number from? In the dashboard the newest I see is `2.7.4+rev1.prod`, and that's also confirmed by running the `./build.sh --list` which lists these versions only for the Jetson TX2:

```
jetson-tx2                     2.7.2+rev10.dev               
jetson-tx2                     2.7.2+rev10.prod              
jetson-tx2                     2.7.2+rev5.dev                
jetson-tx2                     2.7.2+rev5.prod               
jetson-tx2                     2.7.2+rev6.dev                
jetson-tx2                     2.7.2+rev6.prod               
jetson-tx2                     2.7.4+rev1.dev                
jetson-tx2                     2.7.4+rev1.prod 
```

By any chance, are you looking for the `skx2` device type? That one has ` 2.7.4+rev2.prod`...

```
skx2                           2.7.4+rev1.dev                
skx2                           2.7.4+rev1.prod               
skx2                           2.7.4+rev2.dev                
skx2                           2.7.4+rev2.prod
```

**Comment by Davidnet** [comment]
Sorry about that, you are correct, but even with '2.7.4+rev1.prod' it still fails with
```
scripts/Makefile.build:267: recipe for target ‘/usr/src/app/example_module_jetson-tx2_2.7.4+rev1.prod/hello.o’ failed
./arch/arm64/include/asm/opcodes.h:5:43: fatal error: …/…/arm/include/asm/opcodes.h: No such file or directory
```

**Comment by imrehg** [comment]
Checking it out.

**Comment by Davidnet** [comment]
@imrehg were you able to replicate?

**Comment by imrehg** [comment]
@Davidnet yes, I've contacted the team members whose area this is. And apparently already looking at it, starting from your forums post regarding the same issue: https://forums.resin.io/t/jetson-tx2-kernel-module-extension/2175

**Comment by agherzan** [comment]
Assigning to @telphan.

**Comment by agherzan** [comment]
It seems like I can't assign Theodor. It seems there is a problem with the members setup for this repository. @apostolism  can you please take a look as it seems I don't have the permissions to check it out?

**Comment by telphan** [comment]
Acknowledging, just in case. @agherzan

**Comment by Davidnet** [comment]
Maybe trying to put the opcode.h generated? I Haven't been able to solve it.

**Comment by floion** [comment]
@telphan any news on this?

**Comment by telphan** [comment]
@floion yes, it was fixed here (https://github.com/resin-os/module-headers/commit/ce7805a769bde97fa7bcc153bcd8763b94df4513)  also deployed to production.

**Comment by floion** [comment]
Closing as per @telphan 's comment
